# https://taskfile.dev

version: '3'

vars:
  MAIN: go-markdown-code-runner.go

tasks:
  run:
    cmds:
      - go run "{{.MAIN}}" "{{.CLI_ARGS}}"
    # silent: true

  build:
    cmds:
      - task: format
      - go build "{{.MAIN}}"
    # silent: true

  format:
    cmds:
      - go fmt *.go
    # silent: true

  test:
    deps:
      - build
    cmds:
      - ./go-markdown-code-runner README.md
    # silent: true
