# https://taskfile.dev

version: '3'

vars:
  MAIN: main.go

tasks:
  run:
    cmds:
      - go run "{{.MAIN}}" "{{.CLI_ARGS}}"
    # silent: true

  build:
    cmds:
      - task: format
      - go build
    # silent: true

  format:
    cmds:
      - go fmt *.go
    # silent: true

  test:
    deps:
      - build
    cmds:
      - ./go-markdown-code-runner README.md
    # silent: true

  dev:coding-standards:check:
    cmds:
      - task: dev:coding-standards:apply
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore LICENSE.md '*.md' docs/

  dev:coding-standards:apply:
    cmds:
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore LICENSE.md '*.md' docs/ --fix
