# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - go run ./main.go
    # silent: true

  build:
    cmds:
      - task: format
      - task: check
      - go build
    # silent: true

  format:
    cmds:
      - go fmt ./...
    # silent: true

  check:
    cmds:
      - go vet ./...
    # silent: true

  test:
    deps:
      - build
    cmds:
      - ./go-markdown-code-runner README.md
    # silent: true

  dev:coding-standards:check:
    cmds:
      - task: dev:coding-standards:apply
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore LICENSE.md '*.md' docs/

  dev:coding-standards:apply:
    cmds:
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore LICENSE.md '*.md' docs/ --fix
